#pragma once

#include <stdbool.h>
#include <stdint.h>

uint8_t get_key(void);
void keyboard_handler(void);

enum scancode_1 {
    KEY_ESC = 0x01,
    KEY_1 = 0x02,
    KEY_2 = 0x03,
    KEY_3 = 0x04,
    KEY_4 = 0x05,
    KEY_5 = 0x06,
    KEY_6 = 0x07,
    KEY_7 = 0x08,
    KEY_8 = 0x09,
    KEY_9 = 0x0A,
    KEY_0 = 0x0B,
    KEY_MINUS = 0x0C,
    KEY_EQUAL = 0x0D,
    KEY_BACKSPACE = 0x0E,
    KEY_NUMPAD_1 = 0xCF,
    KEY_NUMPAD_2 = 0xD0,
    KEY_NUMPAD_3 = 0xD1,
    KEY_NUMPAD_4 = 0xCB,
    KEY_NUMPAD_5 = 0xCC,
    KEY_NUMPAD_6 = 0xCD,
    KEY_NUMPAD_7 = 0xC7,
    KEY_NUMPAD_8 = 0xC8,
    KEY_NUMPAD_9 = 0xC9,
    KEY_NUMPAD_0 = 0x52,
    KEY_NUMPAD_DOT = 0xD3,
    KEY_NUMPAD_PLUS = 0x4E,
    KEY_NUMPAD_MINUS = 0xCA,
    KEY_TAB = 0x0F,
    KEY_NUMPAD_ASTERISK = 0xB7,
    KEY_Q = 0x10,
    KEY_W = 0x11,
    KEY_E = 0x12,
    KEY_R = 0x13,
    KEY_T = 0x14,
    KEY_Y = 0x15,
    KEY_U = 0x16,
    KEY_I = 0x17,
    KEY_O = 0x18,
    KEY_P = 0x19,
    KEY_SQBRACKET_LEFT = 0x1A,
    KEY_SQBRACKET_RIGHT = 0x1B,
    KEY_ENTER = 0x1C,
    KEY_CTRL_LEFT = 0x1D,
    KEY_A = 0x1E,
    KEY_S = 0x1F,
    KEY_D = 0x20,
    KEY_F = 0x21,
    KEY_G = 0x22,
    KEY_H = 0x23,
    KEY_J = 0x24,
    KEY_K = 0x25,
    KEY_L = 0x26,
    KEY_SEMICOLON = 0x27,
    KEY_SINGLE_QUOTE = 0x28,
    KEY_BACKTICK = 0x29,
    KEY_SHIFT_LEFT = 0x2A,
    KEY_BACKSLASH = 0x2B,
    KEY_Z = 0x2C,
    KEY_X = 0x2D,
    KEY_C = 0x2E,
    KEY_V = 0x2F,
    KEY_B = 0x30,
    KEY_N = 0x31,
    KEY_M = 0x32,
    KEY_COMMA = 0x33,
    KEY_DOT = 0x34,
    KEY_SLASH = 0x35,
    KEY_SHIFT_RIGHT = 0x36,
    KEY_ALT_LEFT = 0x38,
    KEY_SPACE = 0x39,
    KEY_CAPSLOCK = 0x3A,
    KEY_F1 = 0x3B,
    KEY_F2 = 0x3C,
    KEY_F3 = 0x3D,
    KEY_F4 = 0x3E,
    KEY_F5 = 0x3F,
    KEY_F6 = 0x40,
    KEY_F7 = 0x41,
    KEY_F8 = 0x42,
    KEY_F9 = 0x43,
    KEY_F10 = 0x44,
    KEY_NUMLOCK = 0x45,
    KEY_SCROLLLOCK = 0x46,
    KEY_F11 = 0x57,
    KEY_F12 = 0x58,
    KEY_DELETE = 0x53,
    KEY_ARROW_LEFT = 0x4B,
    KEY_ARROW_RIGHT = 0x4D,
};

static const char scancode_map[256] = {
    [KEY_ESC] = 27,
    [KEY_1] = '1',
    [KEY_2] = '2',
    [KEY_3] = '3',
    [KEY_4] = '4',
    [KEY_5] = '5',
    [KEY_6] = '6',
    [KEY_7] = '7',
    [KEY_8] = '8',
    [KEY_9] = '9',
    [KEY_0] = '0',
    [KEY_MINUS] = '-',
    [KEY_EQUAL] = '=',
    [KEY_BACKSPACE] = '\b',
    [KEY_TAB] = '\t',
    [KEY_Q] = 'q',
    [KEY_W] = 'w',
    [KEY_E] = 'e',
    [KEY_R] = 'r',
    [KEY_T] = 't',
    [KEY_Y] = 'y',
    [KEY_U] = 'u',
    [KEY_I] = 'i',
    [KEY_O] = 'o',
    [KEY_P] = 'p',
    [KEY_SQBRACKET_LEFT] = '[',
    [KEY_SQBRACKET_RIGHT] = ']',
    [KEY_ENTER] = '\n',
    [KEY_A] = 'a',
    [KEY_S] = 's',
    [KEY_D] = 'd',
    [KEY_F] = 'f',
    [KEY_G] = 'g',
    [KEY_H] = 'h',
    [KEY_J] = 'j',
    [KEY_K] = 'k',
    [KEY_L] = 'l',
    [KEY_SEMICOLON] = ';',
    [KEY_SINGLE_QUOTE] = '\'',
    [KEY_BACKTICK] = '`',
    [KEY_BACKSLASH] = '\\',
    [KEY_Z] = 'z',
    [KEY_X] = 'x',
    [KEY_C] = 'c',
    [KEY_V] = 'v',
    [KEY_B] = 'b',
    [KEY_N] = 'n',
    [KEY_M] = 'm',
    [KEY_COMMA] = ',',
    [KEY_DOT] = '.',
    [KEY_SLASH] = '/',
    [KEY_SPACE] = ' ',
    [KEY_DELETE] = 127,
};

char kbd_get_last_char(bool wait);
char kbd_get_last_scancode(void);